### ISSUE TITLE
`rangeproof_getheader_impl` return values are changed but call sites are not updated

### ISSUE THREAD

**Issue by apoelstra** [comit-network/rust-secp256k1-zkp#2]
It looks like the only difference between the upstream secp-zkp and the vendored version in this library is that `rangeproof_getheader_impl` returns a more detailed error return code. However, 

1. This is called from `rangeproof_verify`, which will now fail 100% of the time.
2. The new return value is propagated up from `rangeproof_info`, which is in the public API, but again the code is basically converted to the old one by the Rust bindings.

Was this an intentional change? If so, it may make sense to propose it upstream, or at the very least include it as an explicit .patch file which is used by the vendoring script.

**Comment by thomaseizinger** [comment]
This has been fixed by re-vendoring `libsecp256k1-zkp`: https://github.com/comit-network/rust-secp256k1-zkp/blob/0516724f52af8ba6f9bec48e5dcd9377bf350895/secp256k1-zkp-sys/depend/secp256k1/src/modules/rangeproof/rangeproof_impl.h#L487-L538
