### ISSUE TITLE
should update secp256k1-sys/lib.rs to match latest rust-secp

### ISSUE THREAD

**Issue by apoelstra** [comit-network/rust-secp256k1-zkp#3]
We've added all the schnorrsig stuff upstream as well as cleaned up some APIs. I think you can just copy the new lib.rs from upstream then re-add `mod zkp; pub use self::zkp::*` and that's all you need to be up-to-date.

**Comment by thomaseizinger** [comment]
This is obsolete now that we are re-exporting everything from `rust-secp256k1`.
